# 01-mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-password
  namespace: todo-ns # <--- Namespace specified here
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "@root#" # <--- CHANGE THIS TO A STRONG PASSWORD!
